#!/bin/bash

set -f

echo "cron-acme $ACME_CRON singal container $ACME_SIGNAL_CONTAINER"
echo $ACME_CRON' acme.sh --cron --renew-hook "docker-signal -name /'$ACME_SIGNAL_CONTAINER' -signal 1"' | minicron -e
